GTFS_HEADERS = {
    "agency.txt": (
        "agency_id",
        "agency_name",
        "agency_url",
        "agency_timezone",
        "agency_lang",
        "agency_phone",
    ),
    "attributions.txt": (
        "attribution_id",
        "organization_name",
        "attribution_url",
        "is_producer",
        "is_operator",
        "is_authority",
        "is_data_source",
    ),
    "feed_info.txt": (
        "feed_publisher_name",
        "feed_publisher_url",
        "feed_lang",
        "feed_version",
    ),
    "calendar_dates.txt": (
        "date",
        "service_id",
        "exception_type",
    ),
    "routes.txt": (
        "route_id",
        "agency_id",
        "route_short_name",
        "route_long_name",
        "route_type",
        "route_color",
        "route_text_color",
    ),
    "stops.txt": (
        "stop_id",
        "stop_name",
        "stop_code",
        "platform_code",
        "stop_lat",
        "stop_lon",
        "location_type",
        "parent_station",
        "wheelchair_boarding",
        "zone_id",
        "stop_name_stem",
        "town_name",
        "street_name",
    ),
    "trips.txt": (
        "trip_id",
        "route_id",
        "service_id",
        "shape_id",
        "trip_short_name",
        "trip_headsign",
        "direction_id",
        "wheelchair_accessible",
        "hidden_block_id",
        "variant_code",
        "brigade",
        "fleet_type",
    ),
    "stop_times.txt": (
        "trip_id",
        "stop_sequence",
        "stop_id",
        "arrival_time",
        "departure_time",
        "pickup_type",
        "drop_off_type",
        "shape_dist_traveled",
    ),
    "frequencies.txt": (
        "trip_id",
        "start_time",
        "end_time",
        "headway_secs",
        "exact_times",
    ),
    "shapes.txt": (
        "shape_id",
        "shape_pt_sequence",
        "shape_pt_lat",
        "shape_pt_lon",
        "shape_dist_traveled",
    ),
    "fare_attributes.txt": (
        "fare_id",
        "price",
        "currency_type",
        "payment_method",
        "transfers",
        "agency_id",
        "transfer_duration",
    ),
    "fare_rules.txt": (
        "fare_id",
        "route_id",
        "contains_id",
    ),
}
