GTFS_HEADERS = {
    "agency.txt": (
        "agency_id",
        "agency_name",
        "agency_url",
        "agency_timezone",
        "agency_lang",
        "agency_phone",
    ),
    "calendar_dates.txt": (
        "date",
        "service_id",
        "exception_type",
    ),
    "routes.txt": (
        "route_id",
        "agency_id",
        "route_short_name",
        "route_long_name",
        "route_type",
        "route_color",
        "route_text_color",
    ),
    "stops.txt": (
        "stop_id",
        "stop_name",
        "stop_lat",
        "stop_lon",
        "wheelchair_boarding",
    ),
    "trips.txt": (
        "trip_id",
        "route_id",
        "service_id",
        "shape_id",
        "trip_short_name",
        "trip_headsign",
        "wheelchair_accessible",
        "hidden_block_id",
        "brigade",
        "fleet_type",
    ),
    "stop_times.txt": (
        "trip_id",
        "stop_sequence",
        "stop_id",
        "arrival_time",
        "departure_time",
        "pickup_type",
        "drop_off_type",
    ),
    "shapes.txt": (
        "shape_id",
        "shape_pt_sequence",
        "shape_pt_lat",
        "shape_pt_lon",
    ),
}
